status = [
    "clippy",
    "doc",
    "doclinks",
    "features",
    "features (systick)",
    "features (systick,rt)",
    "features (usb-logging)",
    "features (usb-logging,rt)",
    "features (rtic)",
    "features (rtic,rt)",
    "format",
    "precompiled",
    "template",
    "test",
    "xplat (macos-latest)",
    "xplat (ubuntu-latest)",
    "xplat (windows-latest)"
]
delete_merged_branches = true
