language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
  fast_finish: true
before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup target add thumbv7em-none-eabihf
script:
  - export RUST_HOST_TARGET="$(rustc --verbose --version | grep host | cut -d' ' -f2)" 
  - cargo build --verbose --all
  - cargo fmt --all -- --check
  - cargo clippy -- --deny warnings
  # FCB generation crate checks
  - cd imxrt1062-fcb-gen
  - cargo test --target $RUST_HOST_TARGET
  - cargo clippy --target $RUST_HOST_TARGET -- --deny warnings
  - cd ..
  # PAC import tool checks
  - cd tools
  - cargo test --target $RUST_HOST_TARGET
  - cargo clippy --target $RUST_HOST_TARGET -- --deny warnings
  - cd ..