[package]
name = "teensy4-bsp"
version = "0.1.0"
authors = ["Ian McIntyre <ianpmcintyre@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mciantyre/teensy4-rs"
description = """
Rust-based BSP for the Teensy 4.
Part of the teensy4-rs project.
"""

[dependencies]
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12" # Note: not the 'real' cortex-m-rt

[target.thumbv7em-none-eabihf.dependencies]
teensy4-fcb = { path = "teensy4-fcb" }

[dependencies.imxrt-hal]
version = "0.4.0"
features = ["imxrt1062", "rt"]

[dependencies.teensy4-pins]
version = "0.1"
path = "teensy4-pins"

# Tied to "systick" feature, since
# SysTick implements a blocking delay trait
[dependencies.embedded-hal]
version = "0.2.4"
optional = true

# Only need logging when "usb-logging" is enabled
[dependencies.log]
version = "0.4.8"
optional = true

# Only needed when "usb-logging" is enabled
[dependencies.teensy4-usb-sys]
path = "teensy4-usb-sys"
optional = true

[target.thumbv7em-none-eabihf.dev-dependencies]
cortex-m-rtic = "0.5.3"
embedded-hal = "0.2.4"
heapless = "0.5.5"
imxrt-uart-log = "0.2.0"
log = "0.4.8"
nb = "0.1.2"

[dev-dependencies]
panic-halt = "0.2.0"

[workspace]
members = [
    "cortex-m-rt-patch",
    "teensy4-fcb",
    "teensy4-pins",
    "teensy4-rt",
    "teensy4-usb-sys",
]

[features]
# Default features established for prototype development
default = ["usb-logging", "systick"]
# Enables the USB logging stack
#
# This will introduce the teensy4-usb-sys bindings into the build
# graph. It also requires systick, since the USB stack depends on
# the systick counter for timekeeping.
usb-logging = ["systick", "teensy4-usb-sys", "log"]
# Include a definition of the SysTick exception handler. This enables
# a simple delay() spinloop that waits for the timer to elapse.
#
# NOTE: This feature is incompatible with the `rtic` crate as `rtic`
# provides its own `SysTick` definition.
systick = ["embedded-hal"]
# Provides the `Peripherals::steal` constructor required by `rtic`.
#
# NOTE: When using this feature along with the `rtic` crate the
# default features must first be disabled in order to avoid a
# duplicate definition of `SysTick`.
rtic = ["imxrt-hal/rtic"]

# Don't optimize build dependencies, like proc macros.
# Helps with build times.
[profile.release.build-override]
opt-level = 0

# Patch `cortex-m-rt` for reasons described here:
# https://github.com/mciantyre/teensy4-rs#runtime
[patch.crates-io.cortex-m-rt]
path = "cortex-m-rt-patch"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# Temporary patch for testing SRTC feature
[patch.crates-io.imxrt-hal]
git = "https://github.com/imxrt-rs/imxrt-rs"
rev = "a85b279"

[patch.crates-io.imxrt-iomuxc]
git = "https://github.com/imxrt-rs/imxrt-rs"
rev = "a85b279"

##########
# Examples
##########

# Examples that don't need any features

[[example]]
name = "gpt"
required-features = []

[[example]]
name = "led"
required-features = []

[[example]]
name = "pit"
required-features = []

# Examples that use SYSTICK as a timer

[[example]]
name = "systick"
required-features = ["systick"]

# Examples that require USB logging.
# This implies the "systick" feature.

[[example]]
name = "dma_memcpy"
required-features = ["usb-logging"]

[[example]]
name = "dma_spi"
required-features = ["usb-logging"]

[[example]]
name = "dma_uart"
required-features = ["usb-logging"]

[[example]]
name = "i2c"
required-features = ["usb-logging"]

[[example]]
name = "pwm"
required-features = ["usb-logging"]

[[example]]
name = "spi"
required-features = ["usb-logging"]

[[example]]
name = "srtc"
required-features = ["usb-logging"]

[[example]]
name = "timer"
required-features = ["usb-logging"]

[[example]]
name = "uart"
required-features = ["usb-logging"]

[[example]]
name = "usb"
required-features = ["usb-logging"]

[[example]]
name = "usb_writer"
required-features = ["usb-logging"]

# RTIC examples

[[example]]
name = "rtic_led"
required-features = ["rtic"]

[[example]]
name = "rtic_blink"
required-features = ["rtic"]

[[example]]
name = "rtic_uart_log"
required-features = ["rtic"]

[[example]]
name = "rtic_dma_uart_log"
required-features = ["rtic"]
