[package]
name = "teensy4-bsp"
version = "0.1.0"
authors = ["Ian McIntyre <ianpmcintyre@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mciantyre/teensy4-rs"
description = """
Rust-based BSP for the Teensy 4.
Part of the teensy4-rs project.
"""
include = [
    "bin/**/*.h",
    "bin/**/*.c",
    "bin/**/*.s",
    "bin/libt4start.a",
    "bin/libt4usb.a",
    "bin/Makefile",
    "src/*",
    "build.rs",
    "t4link.x",
    "README.md",
    "LICENSE-*"
]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
keywords = [
    "arm",
    "cortex-m",
    "teensy4",
]

[dependencies]
cortex-m = "0.6.2"

[target.thumbv7em-none-eabihf.dependencies.cortex-m-rt]
version = "0.6.12"
optional = true
features = ["device"]

[target.thumbv7em-none-eabihf.dependencies.teensy4-fcb]
path = "teensy4-fcb"
version = "0.2"

[dependencies.imxrt-hal]
version = "0.4.2"
features = ["imxrt1062"]

[dependencies.teensy4-pins]
version = "0.1"
path = "teensy4-pins"

# Tied to "systick" feature, since
# SysTick implements a blocking delay trait
[dependencies.embedded-hal]
version = "0.2.4"
optional = true

# Only need logging when "usb-logging" is enabled
[dependencies.log]
version = "0.4.8"
optional = true

[dev-dependencies]
panic-halt = "0.2.0"

[workspace]
members = [
    "examples/bsp",
    "teensy4-fcb",
    "teensy4-panic",
    "teensy4-pins",
]

[features]
# Default features established for prototype development
default = ["usb-logging", "systick"]
# Enables the USB logging stack
usb-logging = ["log"]
# Include a definition of the SysTick exception handler. This enables
# a simple delay() spinloop that waits for the timer to elapse.
#
# NOTE: This feature is incompatible with the `rtic` crate as `rtic`
# provides its own `SysTick` definition.
systick = ["embedded-hal"]
# Provides the `Peripherals::steal` constructor required by `rtic`.
#
# NOTE: When using this feature along with the `rtic` crate the
# default features must first be disabled in order to avoid a
# duplicate definition of `SysTick`.
rtic = ["imxrt-hal/rtic"]
# Enables cortex-m-rt runtime support
rt = ["cortex-m-rt", "imxrt-hal/rt"]

# Don't optimize build dependencies, like proc macros.
# Helps with build times.
[profile.release.build-override]
opt-level = 0

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
