[workspace]
members = [
    'teensy4-bsp',
    'teensy4-bsp/teensy4-usb-sys',
    'teensy4-examples',
    'imxrt1062-hal',
    'imxrt1062-rt',
    'imxrt1062-pac',
    'imxrt1062-pac/imxrt1062-core',
    'imxrt1062-pac/imxrt1062-ccm',
    'imxrt1062-pac/imxrt1062-ccm-analog',
    'imxrt1062-pac/imxrt1062-dcdc',
    'imxrt1062-pac/imxrt1062-gpio1',
    'imxrt1062-pac/imxrt1062-gpt1',
    'imxrt1062-pac/imxrt1062-iomuxc',
    'imxrt1062-pac/imxrt1062-iomuxc-gpr',
    'imxrt1062-pac/imxrt1062-pit',
    'imxrt1062-pac/imxrt1062-pwm1',
    'teensy4-fcb',
]
exclude = [
    'tools',
    'imxrt1062-fcb-gen',
    'svd/imxrt1062',
]
