[lib]
bench = false
test = false

[package]
authors = ['Ian McIntyre <ianpmcintyre@gmail.com>']
description = '''
Peripheral Access Crates (PAC) for the iMXRT1062 family of processors.
Part of the teensy4-rs project.
'''
edition = '2018'
license = 'MIT OR Apache-2.0'
name = 'imxrt1062-pac'
repository = 'https://github.com/mciantyre/teensy4-rs'
version = '0.1.0'

[dependencies]
cortex-m = '0.6.1'

[dependencies.imxrt1062-ccm]
path = 'imxrt1062-ccm'

[dependencies.imxrt1062-ccm-analog]
path = 'imxrt1062-ccm-analog'

[dependencies.imxrt1062-core]
path = 'imxrt1062-core'

[dependencies.imxrt1062-dcdc]
path = 'imxrt1062-dcdc'

[dependencies.imxrt1062-gpio1]
path = 'imxrt1062-gpio1'

[dependencies.imxrt1062-gpt1]
path = 'imxrt1062-gpt1'

[dependencies.imxrt1062-iomuxc]
path = 'imxrt1062-iomuxc'

[dependencies.imxrt1062-iomuxc-gpr]
path = 'imxrt1062-iomuxc-gpr'

[dependencies.imxrt1062-pit]
path = 'imxrt1062-pit'

[dependencies.imxrt1062-pwm1]
path = 'imxrt1062-pwm1'
