name: Code Checks

on:
  push:
    branches: [ master, staging, trying ]

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup component add rustfmt
    - name: Check code formatting
      uses: actions-rs/cargo@v1
      with:
          command: fmt
          args: --verbose --all -- --check
  
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            target: thumbv7em-none-eabihf
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose --all-features --workspace --examples --target thumbv7em-none-eabihf -- -D warnings
          name: Run clippy

  precompiled:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
      - uses: actions/checkout@v2
      - name: Build runtime support
        run: INSTALL_DEPS=0 make libt4boot
      - name: Build USB stack
        run: INSTALL_DEPS=0 make libt4usb

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Run unit and documentation tests
        run: INSTALL_DEPS=0 make test

  xplat:
    strategy:
      matrix:
        host: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            target: thumbv7em-none-eabihf
            override: true
      - name: Build examples
        run: cargo build --examples
      - name: Build RTIC examples
        run: cargo build --examples --no-default-features --features rtic
