name: Code Checks

on:
  push:
    branches: [ teensy4-bsp-0.1 ]

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup component add rustfmt
    - name: Check formatting of BSP and BSP examples
      uses: actions-rs/cargo@v1
      with:
          command: fmt
          args: --verbose --all -- --check
    - name: Check formatting of RTIC examples
      uses: actions-rs/cargo@v1
      with:
          command: fmt
          args: --verbose --manifest-path examples/rtic/Cargo.toml -- --check
  
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            target: thumbv7em-none-eabihf
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose --workspace --target thumbv7em-none-eabihf -- -D warnings
          name: Run clippy on BSP and BSP examples
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose --manifest-path examples/rtic/Cargo.toml --target thumbv7em-none-eabihf -- -D warnings
          name: Run clippy on RTIC examples

  precompiled:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
      - uses: actions/checkout@v2
      - name: Build runtime support
        run: INSTALL_DEPS=0 make libt4start
      - name: Build USB stack
        run: INSTALL_DEPS=0 make libt4usb

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Run unit and documentation tests
        run: INSTALL_DEPS=0 make test

  xplat:
    strategy:
      matrix:
        host: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            target: thumbv7em-none-eabihf
            override: true
      - name: Build examples
        run: cargo build --workspace
      - name: Build RTIC examples
        run: cargo build --manifest-path examples/rtic/Cargo.toml
  
  # Covers feature combinations that may not already be used in
  # the examples.
  features:
    strategy:
      matrix:
        features: [ "", "systick", "systick,rt", "usb-logging", "usb-logging,rt", "rtic", "rtic,rt" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            target: thumbv7em-none-eabihf
            override: true
      - name: Check features '${{ matrix.features }}'
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -D warnings
        with:
            command: check
            args: --verbose --no-default-features --features=${{ matrix.features }}
