# Use the template to create a new starter teensy4-rs project,
# and make sure it compiles.

name: Check Template

on:
  push:
    branches: [ master, staging, trying ]

jobs:
  template:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools-preview
          target: thumbv7em-none-eabihf
          override: true
      - name: Install cargo-generate
        env:
          PACKAGE: cargo-generate-v0.5.0-x86_64-unknown-linux-musl
        run: |
          curl -LJO https://github.com/ashleygwilliams/cargo-generate/releases/latest/download/${PACKAGE}.tar.gz && \
          tar -xvf ${PACKAGE}.tar.gz && \
          cp ${PACKAGE}/cargo-generate $(dirname $(which cargo)) && \
          cargo generate --help
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: latest
          use-tool-cache: true
      - name: Generate the template
        run: cargo generate --git https://github.com/mciantyre/teensy4-rs-template --name krate
      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Update template to target integration branch
        run: sed -i '' "s/branch = \"master\"/branch = \"${{ steps.extract_branch.outputs.branch }}\"/g" krate/Cargo.toml
      - name: Check the template
        run: cd krate && cargo build && cargo objcopy -- -O ihex krate.hex
