[package]
name = "teensy4-bsp"
version = "0.1.0"
authors = ["Ian McIntyre <ianpmcintyre@gmail.com>"]
edition = "2018"

[dependencies]
imxrt1060-hal = { path = "../imxrt1060-hal" }

[lib]
bench = false
test = false